### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by cglong** [mariusor/bubbles-tree#3]
Hi, I found this repo via charmbracelet/bubbles#233 but noticed it doesn't have a license. I'd recommend MIT to be consistent with the upstream project you're hoping to integrate it with 🙂

Note that, without a license, code is generally assumed to be proprietary and the Charm team will likely not be able to read it.

**Comment by mariusor** [comment]
Yes, I think I didn't add a license in the idea that the project would be merged to charmbracelet/bubbles, but it looks like there's very little interest from the Charm devs to accept external contributions. 

I've added a LICENSE, and yes, MIT is what I would have picked anyway.
